# Generated by Django 3.1 on 2020-08-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blogcount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
